### ISSUE TITLE
List of residence of midburn 2018 participants 

### ISSUE THREAD

**Issue by pandamichal** [Midburn/Statistics#11]
We want to know the segmentation of resedence for the people who participated midburn 2018.
It should display cities only (without the street address).

Thanks!

Panda

**Comment by OriHoch** [comment]
https://production.midburn.org/metabase/question/60

**Comment by pandamichal** [comment]
Thanks @OriHoch !
There are only 1694 results and it doesn't make sense... There should be 11,973 results according to the number of tickets...And can you remove the internationals from the list?

**Comment by OriHoch** [comment]
each row shows the number of users with entered tickets per city

limited to show only israel - 

https://production.midburn.org/metabase/question/61

**Comment by pandamichal** [comment]
Thanks a lot!
