### ISSUE TITLE
How many people it's their first midburn event? 

### ISSUE THREAD

**Issue by pandamichal** [Midburn/Statistics#5]
I need only the number, no other details...
The data for that located at the Drupal users information. When a new profile is opened he fills up a form..on that form they answer the question if it's their first midburn.
![image](https://user-images.githubusercontent.com/34742039/39300897-f2ad9b68-4955-11e8-962f-7208f21cb9c4.png)

And just for fun if there is time...among those who never been in midburn, who was at burning man?

**Comment by OriHoch** [comment]
@pandamichal 
people only fill it when they open the profile, and when people open their profile it's always their first event so I don't think these number are reliable..
here it is anyway (limited to show only users with ticket registrations in 2018 and profiles created in 2018) - https://production.midburn.org/metabase/question/37?ticket_registration_from=2018-01-01&user_created_from=2018-01-01

**Comment by pandamichal** [comment]
I understand.. This year people had to update their profile and sign up for the term and conditions, i'm hoping that they are also updated if it's their first midburn...
The numbers don't really fit, it's true.. 
Thanks!
